apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hwfc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hwfc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hwfc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hwfc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hwfc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jtbs-tenant/rhtap-demo-app/hacbs-test-project-hwfc@sha256:eb4d8dc6334766548782e1fbabc3e6d44b946497e5512b71cadb89332100dd32
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
